source 'https://rubygems.org'
ruby '2.3.0'

gem 'active_model_serializers', '0.10.0.rc3'
gem 'authority',  '3.1.0'
gem 'devise',     '3.5.2'
gem 'devise-async', '0.10.1'
gem 'devise-doorkeeper', '1.1.1'
gem 'doorkeeper', '3.0.1'
gem 'dotenv-rails', '2.0.2'
gem 'highline',   '1.7.8'
gem 'maildown',   '2.0.0'
gem 'merit',      '2.3.3'
gem 'rails',      '4.2.1'
gem 'raygun4ruby', '1.1.9'
gem 'rounding',   '1.0.1'
gem 'pg',         '0.18.2'
gem 'puma',       '2.15.3'
gem 'sidekiq',    '4.1.0'
gem 'sheet_mapper', github: 'dlindahl/sheet_mapper', branch: 'google_drive_updates', require: nil
gem 'sinatra',    '1.4.7', require: nil

group :development, :test do
  gem 'awesome_print'
  gem 'foreman',     '0.78.0'
  gem 'spring'
  gem 'rspec-rails', '3.2.1'
end

group :production do
  gem 'rails_12factor', '0.0.3'
end
