# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

EnvironmentManagerPath = '../ios/sloppymoose/EnvironmentManager.m'

# Generates Obj-C code that exports certain ENV vars into the XCode
def generate_environment
  raise ArgumentError, "No --env specified" if Actions.lane_context[:ENVIRONMENT].nil?
  require 'active_support/inflector'

  erb = ERB.new(File.read("#{EnvironmentManagerPath}.template.erb"), nil, '-')
  file = File.open(EnvironmentManagerPath, 'w')

  @env = {
    API_ORIGIN: ENV['API_ORIGIN'],
    DEBUG: !!ENV['DEBUG'],
    LANE_NAME: Actions.lane_context[:LANE_NAME],
    PLATFORM_NAME: Actions.lane_context[:PLATFORM_NAME],
    ENVIRONMENT: Actions.lane_context[:ENVIRONMENT]
  }

  file.write(erb.result(binding))
  file.close
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."

    File.delete(EnvironmentManagerPath) if File.exists?(EnvironmentManagerPath)
  end

  desc "Development"
  lane :dev do
    generate_environment
    # scan
    # gym(scheme: "sloppymoose") # Build your app - more options available
  end

  desc "Runs all the tests"
  lane :test do
    generate_environment
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    generate_environment

    sigh

    increment_build_number

    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: 'sloppymoose-release', project: './ios/sloppymoose.xcodeproj') # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    generate_environment

    # match(type: "appstore")
    # snapshot
    gym(scheme: 'sloppymoose-release', project: './ios/sloppymoose.xcodeproj') # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    if Actions.lane_context[:ENVIRONMENT] != 'development'
      puts "Don't forget to re-run `DEBUG=true fastlane dev --env development`"
    end
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end



# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md
